# Sales Intelligence Platform Project

## Import relevant libraries

In [1]:
import numpy as np
import pandas as pd

## Loading the data

In [2]:
FILE_PATH = 'data/raw_data/Sales Dataset - Sales Dataset.csv'

data = pd.read_csv(FILE_PATH)
df = data.copy() #making a copy to preserve the integrity of the original dataset
print(f'Data shape: {df.shape}\n')
df.head()

Data shape: (1194, 12)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,Year-Month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

`Key observations:`
- `Order ID` is not unique. It appears the same for different customers, having different orders, state, city and date.
- `Year-Month` is not useful in the OLTP (repetition). It can be derived from `Order Date` when building the OLAP later.

## Data quality checks and Data cleaning

### Standardising the data columns

In [3]:
df.columns

Index(['Order ID', 'Amount', 'Profit', 'Quantity', 'Category', 'Sub-Category',
       'PaymentMode', 'Order Date', 'CustomerName', 'State', 'City',
       'Year-Month'],
      dtype='object')

In [4]:
import re

df.columns = (
    df.columns
    .str.strip()                                               #remove trailing and leading white spaces
    .map(lambda x: re.sub(r'(?<=[a-z])(?=[A-Z])', '_', x))     #replace camel case in headers with underscore
    .str.replace(r'[\s-]', '_', regex=True)                    #replace white spaces and hyphens in headers with underscore
    .str.lower()                                               #convert to lower case                                             
)

df.columns

Index(['order_id', 'amount', 'profit', 'quantity', 'category', 'sub_category',
       'payment_mode', 'order_date', 'customer_name', 'state', 'city',
       'year_month'],
      dtype='object')

### Dropping the year_month column

In [5]:
df.drop(columns=['year_month'], inplace=True)
df.head()

,order_id,amount,profit,quantity,category,sub_category,payment_mode,order_date,customer_name,state,city
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago

### Duplicated values

In [6]:
# checking for duplicated values
df.duplicated().sum()

0

### Null values

In [7]:
# checking for null values
df.isnull().sum()

order_id         0
amount           0
profit           0
quantity         0
category         0
sub_category     0
payment_mode     0
order_date       0
customer_name    0
state            0
city             0
dtype: int64

### Investigating the Order ID issue earlier observed

In [8]:
total_orders = df['order_id'].nunique() #unique items in the order_id column
problematic_orders = df.groupby('order_id')['customer_name'].nunique()[lambda x: x > 1].count() #customers sharing the same order_id 

print(f'Total unique order IDs: {total_orders}')
print(f'Order IDs shared across multiple customers: {problematic_orders}')
print(f'Percentage problematic: {problematic_orders / total_orders * 100:.2f}%\n') #percentage occurrence in the dataset to measure severity

Total unique order IDs: 547
Order IDs shared across multiple customers: 194
Percentage problematic: 35.47%

It has returned that over a third of order_ids are shared across completely different customers. Therefore, it is unreliable as a unique identifier. This would be considered when designing the ERDs for the OLTP and OLAP.

### General information on the dataset

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1194 non-null   object
 1   amount         1194 non-null   int64
 2   profit         1194 non-null   int64
 3   quantity       1194 non-null   int64
 4   category       1194 non-null   object
 5   sub_category   1194 non-null   object
 6   payment_mode   1194 non-null   object
 7   order_date     1194 non-null   object
 8   customer_name  1194 non-null   object
 9   state          1194 non-null   object
 10  city           1194 non-null   object
dtypes: int64(3), object(8)
memory usage: 102.7+ KB

### Standardising data types for amount, profit and order_date

In [10]:
df = df.astype({'amount': float, 'profit': float})
df['order_date'] = pd.to_datetime(df['order_date'])

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1194 non-null   object
 1   amount         1194 non-null   float64
 2   profit         1194 non-null   float64
 3   quantity       1194 non-null   int64
 4   category       1194 non-null   object
 5   sub_category   1194 non-null   object
 6   payment_mode   1194 non-null   object
 7   order_date     1194 non-null   datetime64[ns]
 8   customer_name  1194 non-null   object
 9   state          1194 non-null   object
 10  city           1194 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 102.7+ KB

## Defining the OLTP tables

In [12]:
# creating the oltp file path
import os
os.makedirs('data/oltp', exist_ok=True)

In [13]:
# customers table
customers = df[['customer_name']].copy().drop_duplicates().reset_index(drop=True)
customers.index += 1
customers = customers.reset_index().rename(columns={'index': 'customer_id'})

customers.head()

   customer_id  customer_name
0            1  David Padilla
1            2  Connor Morgan
2            3   Robert Stone
3            4    John Fields
4            5  Clayton Smith

In [14]:
# locations table
locations = df[['city', 'state']].copy().drop_duplicates().reset_index(drop=True)
locations.index += 1
locations = locations.reset_index().rename(columns={'index': 'location_id'})

locations.head()

   location_id         city       state
0            1        Miami     Florida
1            2      Chicago    Illinois
2            3      Buffalo    New York
3            4      Orlando     Florida
4            5  Los Angeles  California

In [15]:
# payment_methods table
payment_methods = df[['payment_mode']].copy().drop_duplicates().reset_index(drop=True)
payment_methods.index += 1
payment_methods = payment_methods.reset_index().rename(columns={'index': 'payment_id'})

payment_methods.head()

   payment_id payment_mode
0           1          UPI
1           2   Debit Card
2           3          EMI
3           4  Credit Card
4           5          COD

In [16]:
# products table
products = df[['category', 'sub_category']].copy().drop_duplicates().reset_index(drop=True)
products.index += 1
products = products.reset_index().rename(columns={'index': 'product_id'})

products.head()

   product_id         category      sub_category
0           1      Electronics  Electronic Games
1           2      Electronics          Printers
2           3  Office Supplies              Pens
3           4      Electronics           Laptops
4           5        Furniture            Tables

In [17]:
# orders

# Merging all dimension IDs back onto the main dataframe
orders_df = df.merge(customers, on='customer_name') \
              .merge(locations, on=['city', 'state']) \
              .merge(payment_methods, on='payment_mode')

# orders table
orders = orders_df[['customer_id', 'order_id', 'order_date', 'location_id', 'payment_id']] \
                  .copy() \
                  .drop_duplicates() \
                  .reset_index(drop=True)
orders.index += 1
orders = orders.reset_index().rename(columns={'index': 'order_pk'})

orders.head()

   order_pk  customer_id order_id order_date  location_id  payment_id
0         1            1  B-26776 2023-06-27            1           1
1         2          110  B-26347 2020-12-21            1           1
2         3          121  B-25400 2021-03-24            1           1
3         4          139  B-25714 2025-02-19            1           1
4         5          258  B-25427 2020-04-04            1           1

In [18]:
duplicates = orders.duplicated(subset=['order_id', 'customer_id', 'order_date'], keep=False)
print(f'Duplicate rows: {duplicates.sum()}')
orders[duplicates].head(10)

Duplicate rows: 538

    order_pk  customer_id order_id order_date  location_id  payment_id
2          3          121  B-25400 2021-03-24            1           1
4          5          258  B-25427 2020-04-04            1           1
5          6          261  B-26224 2023-12-13            1           1
6          7          283  B-26554 2024-10-01            1           1
8          9          437  B-25763 2022-01-18            1           1
9         10          439  B-25465 2020-06-24            1           1
15        16           82  B-25916 2022-12-07            2           1
16        17          171  B-26523 2020-03-31            2           1
19        20          259  B-26224 2023-01-22            2           1
20        21          308  B-26586 2023-09-30            2           1

In [19]:
# order_items table
order_items = orders_df.merge(orders, on=['order_id', 'customer_id', 'order_date', 'location_id', 'payment_id']) \
                       .merge(products, on=['category', 'sub_category'])

order_items = order_items[['order_pk', 'product_id', 'quantity', 'amount', 'profit']] \
                         .copy() \
                         .reset_index(drop=True)
order_items.index += 1
order_items = order_items.reset_index().rename(columns={'index': 'order_item_id'})

order_items.head()

   order_item_id  order_pk  product_id  quantity  amount  profit
0              1         1           1         5  9726.0  1275.0
1              2         4           1        12  6962.0  3429.0
2              3         6           1        15  3953.0  1776.0
3              4         7           1        20  3409.0  1605.0
4              5        15           1         5  9726.0  1275.0

### Saving the tables to csv

In [20]:
customers.to_csv('data/oltp/customers.csv', index=False)
locations.to_csv('data/oltp/locations.csv', index=False)
products.to_csv('data/oltp/products.csv', index=False)
payment_methods.to_csv('data/oltp/payment_methods.csv', index=False)
orders.to_csv('data/oltp/orders.csv', index=False)
order_items.to_csv('data/oltp/order_items.csv', index=False)

## Defining the OLAP tables

In [21]:
# creating the olap file path
os.makedirs('data/olap', exist_ok=True)

In [22]:
# dim_customer
dim_customer = df[['customer_name']].copy().drop_duplicates().reset_index(drop=True)
dim_customer.index += 1
dim_customer = dim_customer.reset_index().rename(columns={'index': 'customer_id'})

# dim_location
dim_location = df[['city', 'state']].copy().drop_duplicates().reset_index(drop=True)
dim_location.index += 1
dim_location = dim_location.reset_index().rename(columns={'index': 'location_id'})

# dim_product
dim_product = df[['category', 'sub_category']].copy().drop_duplicates().reset_index(drop=True)
dim_product.index += 1
dim_product = dim_product.reset_index().rename(columns={'index': 'product_id'})

# dim_payment
dim_payment = df[['payment_mode']].copy().drop_duplicates().reset_index(drop=True)
dim_payment.index += 1
dim_payment = dim_payment.reset_index().rename(columns={'index': 'payment_id'})

# dim_date
dim_date = df[['order_date']].copy().drop_duplicates().reset_index(drop=True)
dim_date.index += 1
dim_date = dim_date.reset_index().rename(columns={'index': 'date_id'})
dim_date['year_month']  = dim_date['order_date'].dt.to_period('M').astype(str)
dim_date['month']       = dim_date['order_date'].dt.month
dim_date['month_name']  = dim_date['order_date'].dt.strftime('%B')
dim_date['quarter']     = dim_date['order_date'].dt.quarter
dim_date['year']        = dim_date['order_date'].dt.year
dim_date['day_of_week'] = dim_date['order_date'].dt.dayofweek
dim_date['is_weekend']  = dim_date['order_date'].dt.dayofweek >= 5

In [23]:
# fact_order_items
fact_order_items = df.copy() \
    .merge(dim_customer, on='customer_name') \
    .merge(dim_location, on=['city', 'state']) \
    .merge(dim_product, on=['category', 'sub_category']) \
    .merge(dim_payment, on='payment_mode') \
    .merge(dim_date, on='order_date')

fact_order_items = fact_order_items[['customer_id', 'location_id', 'product_id', 'payment_id', 'date_id', 'quantity', 'amount', 'profit']] \
    .copy() \
    .reset_index(drop=True)
fact_order_items.index += 1
fact_order_items = fact_order_items.reset_index().rename(columns={'index': 'order_item_id'})

### Saving the tables to csv

In [24]:
dim_customer.to_csv('data/olap/dim_customer.csv', index=False)
dim_location.to_csv('data/olap/dim_location.csv', index=False)
dim_product.to_csv('data/olap/dim_product.csv', index=False)
dim_payment.to_csv('data/olap/dim_payment.csv', index=False)
dim_date.to_csv('data/olap/dim_date.csv', index=False)
fact_order_items.to_csv('data/olap/fact_order_items.csv', index=False)

In [25]:
print(f'customers:        {len(customers)}')
print(f'locations:        {len(locations)}')
print(f'products:         {len(products)}')
print(f'payment_methods:  {len(payment_methods)}')
print(f'orders:           {len(orders)}')
print(f'order_items:      {len(order_items)}')

print(f'\ndim_customer:     {len(dim_customer)}')
print(f'dim_location:     {len(dim_location)}')
print(f'dim_product:      {len(dim_product)}')
print(f'dim_payment:      {len(dim_payment)}')
print(f'dim_date:         {len(dim_date)}')
print(f'fact_order_items: {len(fact_order_items)}')

customers:        802
locations:        18
products:         12
payment_methods:  5
orders:           1098
order_items:      1194

dim_customer:     802
dim_location:     18
dim_product:      12
dim_payment:      5
dim_date:         648
fact_order_items: 1194

## Aggregations and Analysis using the OLAP tables

### Connecting to the OLAP database

In [26]:
from dotenv import load_dotenv

In [27]:
# Loading the .env file
load_dotenv()

DB_HOST     = os.getenv('DB_HOST')
DB_PORT     = os.getenv('DB_PORT')
DB_USER     = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_NAME     = os.getenv('DB_NAME')

# Loading the SQL extension
%load_ext sql

# Connecting to the database
%sql postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}

# Set search path to olap schema
%sql SET search_path TO olap;

 * postgresql://postgres:***@localhost:5432/sales_platform
Done.

[]

### Profit and loss by category, city, and customer

In [28]:
from sqlalchemy import create_engine, event, text

engine = create_engine(
    f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}',
    connect_args={'options': '-csearch_path=olap'}
)

In [29]:
def run_query(query: str) -> pd.DataFrame:
    with engine.connect() as con:
        return pd.read_sql(text(query), con)

In [30]:
query = """
    SELECT
        dc.customer_name,
        dl.city,
        dl.state,
        dp.category,
        SUM(f.amount)                  AS total_revenue,
        SUM(f.profit)                  AS total_profit,
        SUM(f.amount) - SUM(f.profit)  AS total_loss,
        SUM(f.quantity)                AS total_quantity
    FROM fact_order_items f
    JOIN dim_customer dc ON f.customer_id = dc.customer_id
    JOIN dim_location dl ON f.location_id = dl.location_id
    JOIN dim_product  dp ON f.product_id  = dp.product_id
    GROUP BY dc.customer_name, dl.city, dl.state, dp.category
    ORDER BY total_profit DESC
"""

df_pnl = run_query(query)
df_pnl.head(10)

,customer_name,city,state,category,total_revenue,total_profit,total_loss,total_quantity
0,Logan Galloway,New York City,New York,Electronics,21116.0,8840.0,12276.0,34
1,Stephanie Manning,Orlando,Florida,Electronics,21116.0,8840.0,12276.0,34
2,Brent Hernandez,Rochester,New York,Office Supplies,19611.0,7116.0,12495.0,27
3,Susan Burke,Austin,Texas,Office Supplies,19611.0,7116.0,12495.0,27
4,Patrick Williams,Rochester,New York,Office Supplies,19611.0,7116.0,12495.0,27
5,Leslie Bean,Springfield,Illinois,Office Supplies,15093.0,5997.0,9096.0,23
6,Jeffrey Middleton,Buffalo,New York,Office Supplies,15093.0,5997.0,9096.0,23
7,Veronica Kelley,Orlando,Florida,Office Supplies,15093.0,5997.0,9096.0,23
8,James Gutierrez,Rochester,New York,Electronics,15394.0,5886.0,9508.0,26
9,Michael Hunt,Dallas,Texas,Furniture,14736.0,5452.0,9284.0,13

### Order frequency

In [31]:
query = """
    SELECT
        dc.customer_name,
        COUNT(f.order_item_id) AS order_frequency
    FROM fact_order_items f
    JOIN dim_customer dc ON f.customer_id = dc.customer_id
    GROUP BY dc.customer_name
    ORDER BY order_frequency DESC;
"""

df_order_frequency = run_query(query)
df_order_frequency.head(10)

       customer_name  order_frequency
0        Kelly Smith                4
1  Michael Rodriguez                4
2      Claudia Curry                4
3    Christina Davis                4
4  Jacqueline Harris                4
5      Daniel Mosley                4
6    Michelle Bailey                4
7        Scott Lewis                4
8         Cory Evans                4
9       Brett Sutton                4

### High-profit sub-categories

In [32]:
query = """
    SELECT
        dp.category,
        dp.sub_category,
        SUM(f.profit) AS total_profit
    FROM fact_order_items f
    JOIN dim_product dp ON f.product_id = dp.product_id
    GROUP BY dp.category, dp.sub_category
    HAVING SUM(f.profit) > (
        SELECT AVG(sub_profit)
        FROM (
            SELECT SUM(profit) AS sub_profit
            FROM fact_order_items
            GROUP BY product_id
        ) sub
    )
    ORDER BY total_profit DESC;
"""

df_high_profit = run_query(query)
df_high_profit.head(10)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

          category      sub_category  total_profit
0  Office Supplies           Markers      174749.0
1        Furniture            Tables      156796.0
2  Office Supplies             Paper      149723.0
3      Electronics  Electronic Games      148454.0
4      Electronics          Printers      146259.0
5        Furniture             Sofas      142854.0

### Peak months

In [33]:
query = """
    SELECT
        dd.year,
        dd.month,
        dd.month_name,
        SUM(f.profit)          AS total_profit,
        SUM(f.amount)          AS total_revenue,
        COUNT(f.order_item_id) AS total_orders
    FROM fact_order_items f
    JOIN dim_date dd ON f.date_id = dd.date_id
    GROUP BY dd.year, dd.month, dd.month_name
    ORDER BY total_profit DESC;
"""

df_peak_months = run_query(query)
df_peak_months.head(10)

   year  month month_name  total_profit  total_revenue  total_orders
0  2022      8     August       58918.0       198965.0            33
1  2023      7       July       49391.0       181554.0            30
2  2022     12   December       48915.0       204413.0            45
3  2022      6       June       45962.0       146997.0            27
4  2022      1    January       39808.0       145619.0            31
5  2022     10    October       39007.0       155508.0            28
6  2025      1    January       38595.0       112906.0            16
7  2021      3      March       36377.0       103198.0            19
8  2024      7       July       36323.0       129944.0            26
9  2024      6       June       36191.0       140745.0            27

### Cities with revenue above the 95th percentile

In [34]:
query = """
    WITH city_revenue AS (
        SELECT
            dl.city,
            dl.state,
            SUM(f.amount) AS total_revenue
        FROM fact_order_items f
        JOIN dim_location dl ON f.location_id = dl.location_id
        GROUP BY dl.city, dl.state
    ),
    threshold AS (
        SELECT PERCENTILE_CONT(0.95)
        WITHIN GROUP (ORDER BY total_revenue) AS p95
        FROM city_revenue
    )
    SELECT
        cr.city,
        cr.state,
        cr.total_revenue,
        t.p95 AS threshold
    FROM city_revenue cr
    CROSS JOIN threshold t
    WHERE cr.total_revenue > t.p95
    ORDER BY cr.total_revenue DESC;
"""

df_high_revenue_cities = run_query(query)
df_high_revenue_cities.head(10)

      city    state  total_revenue  threshold
0  Orlando  Florida       452158.0   441823.7

### Average monthly sales per product

In [35]:
query = """
    SELECT
        dp.category,
        dp.sub_category,
        dd.month_name,
        dd.year,
        AVG(f.amount) AS avg_monthly_sales
    FROM fact_order_items f
    JOIN dim_product dp ON f.product_id = dp.product_id
    JOIN dim_date    dd ON f.date_id    = dd.date_id
    GROUP BY
        dp.category,
        dp.sub_category,
        dd.month_name,
        dd.year
    ORDER BY avg_monthly_sales DESC;
"""

df_avg_monthly_sales = run_query(query)
df_avg_monthly_sales.head(10)

          category      sub_category month_name  year  avg_monthly_sales
0  Office Supplies           Markers       June  2020             9965.0
1  Office Supplies             Paper   February  2024             9894.0
2  Office Supplies           Binders   February  2025             9874.0
3      Electronics  Electronic Games  September  2022             9851.0
4  Office Supplies             Paper      March  2025             9845.0
5        Furniture         Bookcases   December  2023             9842.0
6        Furniture            Tables       June  2022             9835.0
7        Furniture            Chairs     August  2021             9820.0
8  Office Supplies           Binders      March  2025             9776.0
9  Office Supplies              Pens       July  2021             9758.5

### Aggregated monthly profits, top customers, and quantity sold per category

In [36]:
# -- Monthly profits
query = """
    SELECT
        dd.year,
        dd.month,
        dd.month_name,
        SUM(f.profit) AS monthly_profit
    FROM fact_order_items f
    JOIN dim_date dd ON f.date_id = dd.date_id
    GROUP BY dd.year, dd.month, dd.month_name
    ORDER BY dd.year, dd.month;
"""

df_monthly_profits = run_query(query)
df_monthly_profits.head(10)

   year  month month_name  monthly_profit
0  2020      3      March          6192.0
1  2020      4      April         36156.0
2  2020      5        May         24294.0
3  2020      6       June          9489.0
4  2020      7       July         12008.0
5  2020      8     August         27824.0
6  2020      9  September         29876.0
7  2020     10    October         24776.0
8  2020     11   November         28979.0
9  2020     12   December         24509.0

In [37]:
# -- Top customers
query = """
    SELECT
        dc.customer_name,
        SUM(f.profit)          AS total_profit,
        SUM(f.amount)          AS total_revenue,
        COUNT(f.order_item_id) AS total_orders
    FROM fact_order_items f
    JOIN dim_customer dc ON f.customer_id = dc.customer_id
    GROUP BY dc.customer_name
    ORDER BY total_profit DESC
    LIMIT 10;
"""

df_top_customers = run_query(query)
df_top_customers.head(10)

          customer_name  total_profit  total_revenue  total_orders
0        Logan Galloway        8840.0        21116.0             3
1     Stephanie Manning        8840.0        21116.0             3
2            Cory Evans        7790.0        28557.0             4
3  Mr. Ralph Garcia Jr.        7275.0        22589.0             3
4          Maria Thomas        7198.0        15280.0             2
5      Nicholas Johnson        7198.0        15280.0             2
6           Kelly Smith        7166.0        23333.0             4
7       Sabrina Hartman        7166.0        23333.0             4
8      Patrick Williams        7116.0        19611.0             2
9       Brent Hernandez        7116.0        19611.0             2

In [38]:
# -- Quantity sold per category
query = """
    SELECT
        dp.category,
        dp.sub_category,
        SUM(f.quantity) AS total_quantity
    FROM fact_order_items f
    JOIN dim_product dp ON f.product_id = dp.product_id
    GROUP BY dp.category, dp.sub_category
    ORDER BY total_quantity DESC;
"""

df_quantity_category = run_query(query)
df_quantity_category.head(10)

          category      sub_category  total_quantity
0        Furniture            Tables            1303
1        Furniture             Sofas            1233
2      Electronics  Electronic Games            1220
3  Office Supplies              Pens            1204
4  Office Supplies           Markers            1173
5      Electronics          Printers            1124
6        Furniture         Bookcases            1030
7  Office Supplies             Paper             981
8      Electronics            Phones             980
9      Electronics           Laptops             934

### Filtered cities with low profitability

In [39]:
query = """
    WITH city_profit AS (
        SELECT
            dl.city,
            dl.state,
            SUM(f.profit) AS total_profit
        FROM fact_order_items f
        JOIN dim_location dl ON f.location_id = dl.location_id
        GROUP BY dl.city, dl.state
    ),
    threshold AS (
        SELECT AVG(total_profit) AS avg_profit
        FROM city_profit
    )
    SELECT
        cp.city,
        cp.state,
        cp.total_profit,
        t.avg_profit AS benchmark
    FROM city_profit cp
    CROSS JOIN threshold t
    WHERE cp.total_profit < t.avg_profit
    ORDER BY cp.total_profit ASC;
"""

df_low_profit_cities = run_query(query)
df_low_profit_cities.head(10)

          city       state  total_profit     benchmark
0     Columbus        Ohio       56277.0  89483.166667
1  Los Angeles  California       69264.0  89483.166667
2        Tampa     Florida       70842.0  89483.166667
3      Houston       Texas       72659.0  89483.166667
4       Peoria    Illinois       76106.0  89483.166667
5   Cincinnati        Ohio       78788.0  89483.166667
6      Chicago    Illinois       80061.0  89483.166667
7    Cleveland        Ohio       81454.0  89483.166667
8       Austin       Texas       82638.0  89483.166667
9  Springfield    Illinois       84205.0  89483.166667